#!/usr/bin/env bash
# Gate A -- prove the backbone reproduces upstream behaviour from a clean checkout.
#
#   FSA Python reference  <->  FSA Verilator  <->  FSA U55C FPGA
#
# Leg 3 cannot run on this machine (no Vivado, no U55C card, XDMA rescan needs root --
# see rpu/DECISIONS.md D-102). It is reported SKIP, never PASS. Two-way agreement is a
# weaker claim than the gate asks for; say so rather than rounding it up.
set -uo pipefail
CY=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$CY" || exit 1
CONFIG=${CONFIG:-FSA4X4Fp16Config}
PIN=fa8665b74347bae0a0e99a8769bc973f26c9a30c
fail=0
say() { printf '\n== %s ==\n' "$1"; }
chk() { if eval "$2" >/dev/null 2>&1; then echo "  PASS  $1"; else echo "  FAIL  $1"; fail=1; fi; }

say "0. Pinned checkout"
chk "chipyard-fsa at pinned ${PIN:0:8}" "[ \"\$(git rev-parse HEAD)\" = $PIN ]"
chk "generators/fsa submodule populated" "[ -f generators/fsa/src/main/scala/fsa/AXI4FSA.scala ]"
chk "conda env built"                    "[ -d .conda-env ]"
chk "env.sh present"                     "[ -f env.sh ]"

say "1. Verilator simulator for $CONFIG"
# env.sh is generated by build-setup.sh and returns 1 unless `conda` is already on
# PATH -- it calls `conda info --base` to find the profile script. Miniforge first
# (D-101), then uv for the FSA Python API.
export PATH="$HOME/miniforge3/bin:$HOME/miniforge3/condabin:$HOME/.local/bin:$PATH"
chk "conda on PATH for env.sh" "command -v conda"
# shellcheck disable=SC1091
source env.sh
chk "simulator builds" "make -C sims/verilator CONFIG=$CONFIG -j\$(nproc)"

say "2. FSA Python reference vs Verilator vs Torch"
chk "seq_q=4 seq_kv=4 agrees with torch" \
    "(cd generators/fsa/python && uv run main.py --seq_q 4 --seq_kv 4 --config $CONFIG --diff)"

say "3. U55C FPGA"
echo "  SKIP  no Vivado install, no Xilinx PCIe device, XDMA rescan needs root"

echo
if [ $fail -eq 0 ]; then
  echo "GATE A: simulation legs PASSED; FPGA leg SKIPPED -- gate is NOT fully closed"
else
  echo "GATE A: FAILED -- stop before RPU development"
fi
exit $fail
